// frontend/src/app/routes/upload/upload.component.ts
import { Component, OnInit } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { NgxDropzoneChangeEvent } from 'ngx-dropzone';
import { ProcessingViewMetadata } from '../../models/processing-view-metadata';

@Component({
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.scss'],
})
export class UploadComponent {
  constructor(private snackBar: MatSnackBar, private router: Router) {}
  onSelect(event: NgxDropzoneChangeEvent) {
    if (event.addedFiles.length > 1) {
      this.snackBar.open(
        'You uploaded multiple images, only one has been uploaded'
      );
    }

    const metadata: ProcessingViewMetadata = {
      imageFile: event.addedFiles[0],
    };
    this.router.navigate(['/processing'], { state: metadata });
  }
}

<div class="content-border">
  <ngx-dropzone (change)="onSelect($event)">
    <div class="centered">
      <h1>Upload Image</h1>
      <p>Drag and drop an image here, or click to select an image</p>
    </div>
  </ngx-dropzone>
</div>

// frontend/src/routes/upload/upload.tsx
import { useSnackbar } from 'notistack';
import Dropzone from 'react-dropzone';
import { useNavigate } from 'react-router-dom';

import Centered from '../../components/centered/centered';
import { ProcessingViewMetadata } from '../processing/processing';

export default function UploadView() {
  const navigate = useNavigate();
  const snackbar = useSnackbar();

  function onAcceptedFiles(files: File[]) {
    if (files.length > 1) {
      snackbar.enqueueSnackbar(
        'You uploaded multiple images, only one has been uploaded',
        {
          variant: 'info',
        },
      );
    }

    const metadata: ProcessingViewMetadata = {
      imageFile: files[0],
    };
    navigate('/processing', {
      state: metadata,
    });
  }

  return (
    <>
      <Dropzone onDrop={onAcceptedFiles}>
        {({ getRootProps, getInputProps }) => (
          <section className="contentwindow">
            <Centered {...getRootProps()}>
              <input {...getInputProps()} />

              <h1>Upload Image</h1>
              <p>Drag and drop an image here, or click to select an image</p>
            </Centered>
          </section>
        )}
      </Dropzone>
    </>
  );
}
